from django.db import models
from django.urls import reverse

# --- 심리검사문항.
class Psytestsheet(models.Model):
    # title = models.CharField('TITLE', max_length=100, blank=True)
    psytest_nm = models.CharField('PSYTEST NAME', max_length=100)
    description = models.CharField('DESCRIPTION', max_length=200, blank=True, help_text='simple description text.')
    is_effect_verify = models.BooleanField('IS EFFECT VERIFY', default=False)
    start_age = models.IntegerField('START_AGE')
    end_age = models.IntegerField('END AGE')
    q1   = models.CharField("Q1",   max_length=200, blank=True, default=" ")
    q2   = models.CharField("Q2",   max_length=200, blank=True, default=" ")
    q3   = models.CharField("Q3",   max_length=200, blank=True, default=" ")
    q4   = models.CharField("Q4",   max_length=200, blank=True, default=" ")
    q5   = models.CharField("Q5",   max_length=200, blank=True, default=" ")
    q6   = models.CharField("Q6",   max_length=200, blank=True, default=" ")
    q7   = models.CharField("Q7",   max_length=200, blank=True, default=" ")
    q8   = models.CharField("Q8",   max_length=200, blank=True, default=" ")
    q9   = models.CharField("Q9",   max_length=200, blank=True, default=" ")
    q10  = models.CharField("Q10",   max_length=200, blank=True, default=" ")
    q11  = models.CharField("Q11",   max_length=200, blank=True, default=" ")
    q12  = models.CharField("Q12",   max_length=200, blank=True, default=" ")
    q13  = models.CharField("Q13",   max_length=200, blank=True, default=" ")
    q14  = models.CharField("Q14",   max_length=200, blank=True, default=" ")
    q15  = models.CharField("Q15",   max_length=200, blank=True, default=" ")
    q16  = models.CharField("Q16",   max_length=200, blank=True, default=" ")
    q17  = models.CharField("Q17",   max_length=200, blank=True, default=" ")
    q18  = models.CharField("Q18",   max_length=200, blank=True, default=" ")
    q19  = models.CharField("Q19",   max_length=200, blank=True, default=" ")
    q20  = models.CharField("Q20",   max_length=200, blank=True, default=" ")
    q21  = models.CharField("Q21",   max_length=200, blank=True, default=" ")
    q22  = models.CharField("Q22",   max_length=200, blank=True, default=" ")
    q23  = models.CharField("Q23",   max_length=200, blank=True, default=" ")
    q24  = models.CharField("Q24",   max_length=200, blank=True, default=" ")
    q25  = models.CharField("Q25",   max_length=200, blank=True, default=" ")
    q26  = models.CharField("Q26",   max_length=200, blank=True, default=" ")
    q27  = models.CharField("Q27",   max_length=200, blank=True, default=" ")
    q28  = models.CharField("Q28",   max_length=200, blank=True, default=" ")
    q29  = models.CharField("Q29",   max_length=200, blank=True, default=" ")
    q30  = models.CharField("Q30",   max_length=200, blank=True, default=" ")
    q31  = models.CharField("Q31",   max_length=200, blank=True, default=" ")
    q32  = models.CharField("Q32",   max_length=200, blank=True, default=" ")
    q33  = models.CharField("Q33",   max_length=200, blank=True, default=" ")
    q34  = models.CharField("Q34",   max_length=200, blank=True, default=" ")
    q35  = models.CharField("Q35",   max_length=200, blank=True, default=" ")
    q36  = models.CharField("Q36",   max_length=200, blank=True, default=" ")
    q37  = models.CharField("Q37",   max_length=200, blank=True, default=" ")
    q38  = models.CharField("Q38",   max_length=200, blank=True, default=" ")
    q39  = models.CharField("Q39",   max_length=200, blank=True, default=" ")
    q40  = models.CharField("Q40",   max_length=200, blank=True, default=" ")
    q41  = models.CharField("Q41",   max_length=200, blank=True, default=" ")
    q42  = models.CharField("Q42",   max_length=200, blank=True, default=" ")
    q43  = models.CharField("Q43",   max_length=200, blank=True, default=" ")
    q44  = models.CharField("Q44",   max_length=200, blank=True, default=" ")
    q45  = models.CharField("Q45",   max_length=200, blank=True, default=" ")
    q46  = models.CharField("Q46",   max_length=200, blank=True, default=" ")
    q47  = models.CharField("Q47",   max_length=200, blank=True, default=" ")
    q48  = models.CharField("Q48",   max_length=200, blank=True, default=" ")
    q49  = models.CharField("Q49",   max_length=200, blank=True, default=" ")
    q50  = models.CharField("Q50",   max_length=200, blank=True, default=" ")
    q51  = models.CharField("Q51",   max_length=200, blank=True, default=" ")
    q52  = models.CharField("Q52",   max_length=200, blank=True, default=" ")
    q53  = models.CharField("Q53",   max_length=200, blank=True, default=" ")
    q54  = models.CharField("Q54",   max_length=200, blank=True, default=" ")
    q55  = models.CharField("Q55",   max_length=200, blank=True, default=" ")
    q56  = models.CharField("Q56",   max_length=200, blank=True, default=" ")
    q57  = models.CharField("Q57",   max_length=200, blank=True, default=" ")
    q58  = models.CharField("Q58",   max_length=200, blank=True, default=" ")
    q59  = models.CharField("Q59",   max_length=200, blank=True, default=" ")
    q60  = models.CharField("Q60",   max_length=200, blank=True, default=" ")
    q61  = models.CharField("Q61",   max_length=200, blank=True, default=" ")
    q62  = models.CharField("Q62",   max_length=200, blank=True, default=" ")
    q63  = models.CharField("Q63",   max_length=200, blank=True, default=" ")
    q64  = models.CharField("Q64",   max_length=200, blank=True, default=" ")
    q65  = models.CharField("Q65",   max_length=200, blank=True, default=" ")
    q66  = models.CharField("Q66",   max_length=200, blank=True, default=" ")
    q67  = models.CharField("Q67",   max_length=200, blank=True, default=" ")
    q68  = models.CharField("Q68",   max_length=200, blank=True, default=" ")
    q69  = models.CharField("Q69",   max_length=200, blank=True, default=" ")
    q70  = models.CharField("Q70",   max_length=200, blank=True, default=" ")
    q71  = models.CharField("Q71",   max_length=200, blank=True, default=" ")
    q72  = models.CharField("Q72",   max_length=200, blank=True, default=" ")
    q73  = models.CharField("Q73",   max_length=200, blank=True, default=" ")
    q74  = models.CharField("Q74",   max_length=200, blank=True, default=" ")
    q75  = models.CharField("Q75",   max_length=200, blank=True, default=" ")
    q76  = models.CharField("Q76",   max_length=200, blank=True, default=" ")
    q77  = models.CharField("Q77",   max_length=200, blank=True, default=" ")
    q78  = models.CharField("Q78",   max_length=200, blank=True, default=" ")
    q79  = models.CharField("Q79",   max_length=200, blank=True, default=" ")
    q80  = models.CharField("Q80",   max_length=200, blank=True, default=" ")
    q81  = models.CharField("Q81",   max_length=200, blank=True, default=" ")
    q82  = models.CharField("Q82",   max_length=200, blank=True, default=" ")
    q83  = models.CharField("Q83",   max_length=200, blank=True, default=" ")
    q84  = models.CharField("Q84",   max_length=200, blank=True, default=" ")
    q85  = models.CharField("Q85",   max_length=200, blank=True, default=" ")
    q86  = models.CharField("Q86",   max_length=200, blank=True, default=" ")
    q87  = models.CharField("Q87",   max_length=200, blank=True, default=" ")
    q88  = models.CharField("Q88",   max_length=200, blank=True, default=" ")
    q89  = models.CharField("Q89",   max_length=200, blank=True, default=" ")
    q90  = models.CharField("Q90",   max_length=200, blank=True, default=" ")
    q91  = models.CharField("Q91",   max_length=200, blank=True, default=" ")
    q92  = models.CharField("Q92",   max_length=200, blank=True, default=" ")
    q93  = models.CharField("Q93",   max_length=200, blank=True, default=" ")
    q94  = models.CharField("Q94",   max_length=200, blank=True, default=" ")
    q95  = models.CharField("Q95",   max_length=200, blank=True, default=" ")
    q96  = models.CharField("Q96",   max_length=200, blank=True, default=" ")
    q97  = models.CharField("Q97",   max_length=200, blank=True, default=" ")
    q98  = models.CharField("Q98",   max_length=200, blank=True, default=" ")
    q99  = models.CharField("Q99",   max_length=200, blank=True, default=" ")
    q100  = models.CharField("Q100",   max_length=200, blank=True, default=" ")
    q1_1 = models.CharField("Q1_1", max_length=200, blank=True, default=" ")
    q1_2 = models.CharField("Q1_2", max_length=200, blank=True, default=" ")
    q1_3 = models.CharField("Q1_3", max_length=200, blank=True, default=" ")
    q1_4 = models.CharField("Q1_4", max_length=200, blank=True, default=" ")
    q1_5 = models.CharField("Q1_5", max_length=200, blank=True, default=" ")
    q1_6 = models.CharField("Q1_6", max_length=200, blank=True, default=" ")
    q1_7 = models.CharField("Q1_7", max_length=200, blank=True, default=" ")
    q2_1 = models.CharField("Q2_1", max_length=200, blank=True, default=" ")
    q2_2 = models.CharField("Q2_2", max_length=200, blank=True, default=" ")
    q2_3 = models.CharField("Q2_3", max_length=200, blank=True, default=" ")
    q2_4 = models.CharField("Q2_4", max_length=200, blank=True, default=" ")
    q2_5 = models.CharField("Q2_5", max_length=200, blank=True, default=" ")
    q2_6 = models.CharField("Q2_6", max_length=200, blank=True, default=" ")
    q2_7 = models.CharField("Q2_7", max_length=200, blank=True, default=" ")
    q3_1 = models.CharField("Q3_1", max_length=200, blank=True, default=" ")
    q3_2 = models.CharField("Q3_2", max_length=200, blank=True, default=" ")
    q3_3 = models.CharField("Q3_3", max_length=200, blank=True, default=" ")
    q3_4 = models.CharField("Q3_4", max_length=200, blank=True, default=" ")
    q3_5 = models.CharField("Q3_5", max_length=200, blank=True, default=" ")
    q3_6 = models.CharField("Q3_6", max_length=200, blank=True, default=" ")
    q3_7 = models.CharField("Q3_7", max_length=200, blank=True, default=" ")
    q4_1 = models.CharField("Q4_1", max_length=200, blank=True, default=" ")
    q4_2 = models.CharField("Q4_2", max_length=200, blank=True, default=" ")
    q4_3 = models.CharField("Q4_3", max_length=200, blank=True, default=" ")
    q4_4 = models.CharField("Q4_4", max_length=200, blank=True, default=" ")
    q4_5 = models.CharField("Q4_5", max_length=200, blank=True, default=" ")
    q4_6 = models.CharField("Q4_6", max_length=200, blank=True, default=" ")
    q4_7 = models.CharField("Q4_7", max_length=200, blank=True, default=" ")
    q5_1 = models.CharField("Q5_1", max_length=200, blank=True, default=" ")
    q5_2 = models.CharField("Q5_2", max_length=200, blank=True, default=" ")
    q5_3 = models.CharField("Q5_3", max_length=200, blank=True, default=" ")
    q5_4 = models.CharField("Q5_4", max_length=200, blank=True, default=" ")
    q5_5 = models.CharField("Q5_5", max_length=200, blank=True, default=" ")
    q5_6 = models.CharField("Q5_6", max_length=200, blank=True, default=" ")
    q5_7 = models.CharField("Q5_7", max_length=200, blank=True, default=" ")
    q6_1 = models.CharField("Q6_1", max_length=200, blank=True, default=" ")
    q6_2 = models.CharField("Q6_2", max_length=200, blank=True, default=" ")
    q6_3 = models.CharField("Q6_3", max_length=200, blank=True, default=" ")
    q6_4 = models.CharField("Q6_4", max_length=200, blank=True, default=" ")
    q6_5 = models.CharField("Q6_5", max_length=200, blank=True, default=" ")
    q6_6 = models.CharField("Q6_6", max_length=200, blank=True, default=" ")
    q6_7 = models.CharField("Q6_7", max_length=200, blank=True, default=" ")
    q7_1 = models.CharField("Q7_1", max_length=200, blank=True, default=" ")
    q7_2 = models.CharField("Q7_2", max_length=200, blank=True, default=" ")
    q7_3 = models.CharField("Q7_3", max_length=200, blank=True, default=" ")
    q7_4 = models.CharField("Q7_4", max_length=200, blank=True, default=" ")
    q7_5 = models.CharField("Q7_5", max_length=200, blank=True, default=" ")
    q7_6 = models.CharField("Q7_6", max_length=200, blank=True, default=" ")
    q7_7 = models.CharField("Q7_7", max_length=200, blank=True, default=" ")
    q8_1 = models.CharField("Q8_1", max_length=200, blank=True, default=" ")
    q8_2 = models.CharField("Q8_2", max_length=200, blank=True, default=" ")
    q8_3 = models.CharField("Q8_3", max_length=200, blank=True, default=" ")
    q8_4 = models.CharField("Q8_4", max_length=200, blank=True, default=" ")
    q8_5 = models.CharField("Q8_5", max_length=200, blank=True, default=" ")
    q8_6 = models.CharField("Q8_6", max_length=200, blank=True, default=" ")
    q8_7 = models.CharField("Q8_7", max_length=200, blank=True, default=" ")
    q9_1 = models.CharField("Q9_1", max_length=200, blank=True, default=" ")
    q9_2 = models.CharField("Q9_2", max_length=200, blank=True, default=" ")
    q9_3 = models.CharField("Q9_3", max_length=200, blank=True, default=" ")
    q9_4 = models.CharField("Q9_4", max_length=200, blank=True, default=" ")
    q9_5 = models.CharField("Q9_5", max_length=200, blank=True, default=" ")
    q9_6 = models.CharField("Q9_6", max_length=200, blank=True, default=" ")
    q9_7 = models.CharField("Q9_7", max_length=200, blank=True, default=" ")
    q10_1 = models.CharField("Q10_1", max_length=200, blank=True, default=" ")
    q10_2 = models.CharField("Q10_2", max_length=200, blank=True, default=" ")
    q10_3 = models.CharField("Q10_3", max_length=200, blank=True, default=" ")
    q10_4 = models.CharField("Q10_4", max_length=200, blank=True, default=" ")
    q10_5 = models.CharField("Q10_5", max_length=200, blank=True, default=" ")
    q10_6 = models.CharField("Q10_6", max_length=200, blank=True, default=" ")
    q10_7 = models.CharField("Q10_7", max_length=200, blank=True, default=" ")
    q11_1 = models.CharField("Q11_1", max_length=200, blank=True, default=" ")
    q11_2 = models.CharField("Q11_2", max_length=200, blank=True, default=" ")
    q11_3 = models.CharField("Q11_3", max_length=200, blank=True, default=" ")
    q11_4 = models.CharField("Q11_4", max_length=200, blank=True, default=" ")
    q11_5 = models.CharField("Q11_5", max_length=200, blank=True, default=" ")
    q11_6 = models.CharField("Q11_6", max_length=200, blank=True, default=" ")
    q11_7 = models.CharField("Q11_7", max_length=200, blank=True, default=" ")
    q12_1 = models.CharField("Q12_1", max_length=200, blank=True, default=" ")
    q12_2 = models.CharField("Q12_2", max_length=200, blank=True, default=" ")
    q12_3 = models.CharField("Q12_3", max_length=200, blank=True, default=" ")
    q12_4 = models.CharField("Q12_4", max_length=200, blank=True, default=" ")
    q12_5 = models.CharField("Q12_5", max_length=200, blank=True, default=" ")
    q12_6 = models.CharField("Q12_6", max_length=200, blank=True, default=" ")
    q12_7 = models.CharField("Q12_7", max_length=200, blank=True, default=" ")
    q13_1 = models.CharField("Q13_1", max_length=200, blank=True, default=" ")
    q13_2 = models.CharField("Q13_2", max_length=200, blank=True, default=" ")
    q13_3 = models.CharField("Q13_3", max_length=200, blank=True, default=" ")
    q13_4 = models.CharField("Q13_4", max_length=200, blank=True, default=" ")
    q13_5 = models.CharField("Q13_5", max_length=200, blank=True, default=" ")
    q13_6 = models.CharField("Q13_6", max_length=200, blank=True, default=" ")
    q13_7 = models.CharField("Q13_7", max_length=200, blank=True, default=" ")
    q14_1 = models.CharField("Q14_1", max_length=200, blank=True, default=" ")
    q14_2 = models.CharField("Q14_2", max_length=200, blank=True, default=" ")
    q14_3 = models.CharField("Q14_3", max_length=200, blank=True, default=" ")
    q14_4 = models.CharField("Q14_4", max_length=200, blank=True, default=" ")
    q14_5 = models.CharField("Q14_5", max_length=200, blank=True, default=" ")
    q14_6 = models.CharField("Q14_6", max_length=200, blank=True, default=" ")
    q14_7 = models.CharField("Q14_7", max_length=200, blank=True, default=" ")
    q15_1 = models.CharField("Q15_1", max_length=200, blank=True, default=" ")
    q15_2 = models.CharField("Q15_2", max_length=200, blank=True, default=" ")
    q15_3 = models.CharField("Q15_3", max_length=200, blank=True, default=" ")
    q15_4 = models.CharField("Q15_4", max_length=200, blank=True, default=" ")
    q15_5 = models.CharField("Q15_5", max_length=200, blank=True, default=" ")
    q15_6 = models.CharField("Q15_6", max_length=200, blank=True, default=" ")
    q15_7 = models.CharField("Q15_7", max_length=200, blank=True, default=" ")
    q16_1 = models.CharField("Q16_1", max_length=200, blank=True, default=" ")
    q16_2 = models.CharField("Q16_2", max_length=200, blank=True, default=" ")
    q16_3 = models.CharField("Q16_3", max_length=200, blank=True, default=" ")
    q16_4 = models.CharField("Q16_4", max_length=200, blank=True, default=" ")
    q16_5 = models.CharField("Q16_5", max_length=200, blank=True, default=" ")
    q16_6 = models.CharField("Q16_6", max_length=200, blank=True, default=" ")
    q16_7 = models.CharField("Q16_7", max_length=200, blank=True, default=" ")
    q17_1 = models.CharField("Q17_1", max_length=200, blank=True, default=" ")
    q17_2 = models.CharField("Q17_2", max_length=200, blank=True, default=" ")
    q17_3 = models.CharField("Q17_3", max_length=200, blank=True, default=" ")
    q17_4 = models.CharField("Q17_4", max_length=200, blank=True, default=" ")
    q17_5 = models.CharField("Q17_5", max_length=200, blank=True, default=" ")
    q17_6 = models.CharField("Q17_6", max_length=200, blank=True, default=" ")
    q17_7 = models.CharField("Q17_7", max_length=200, blank=True, default=" ")
    q18_1 = models.CharField("Q18_1", max_length=200, blank=True, default=" ")
    q18_2 = models.CharField("Q18_2", max_length=200, blank=True, default=" ")
    q18_3 = models.CharField("Q18_3", max_length=200, blank=True, default=" ")
    q18_4 = models.CharField("Q18_4", max_length=200, blank=True, default=" ")
    q18_5 = models.CharField("Q18_5", max_length=200, blank=True, default=" ")
    q18_6 = models.CharField("Q18_6", max_length=200, blank=True, default=" ")
    q18_7 = models.CharField("Q18_7", max_length=200, blank=True, default=" ")
    q19_1 = models.CharField("Q19_1", max_length=200, blank=True, default=" ")
    q19_2 = models.CharField("Q19_2", max_length=200, blank=True, default=" ")
    q19_3 = models.CharField("Q19_3", max_length=200, blank=True, default=" ")
    q19_4 = models.CharField("Q19_4", max_length=200, blank=True, default=" ")
    q19_5 = models.CharField("Q19_5", max_length=200, blank=True, default=" ")
    q19_6 = models.CharField("Q19_6", max_length=200, blank=True, default=" ")
    q19_7 = models.CharField("Q19_7", max_length=200, blank=True, default=" ")
    q20_1 = models.CharField("Q20_1", max_length=200, blank=True, default=" ")
    q20_2 = models.CharField("Q20_2", max_length=200, blank=True, default=" ")
    q20_3 = models.CharField("Q20_3", max_length=200, blank=True, default=" ")
    q20_4 = models.CharField("Q20_4", max_length=200, blank=True, default=" ")
    q20_5 = models.CharField("Q20_5", max_length=200, blank=True, default=" ")
    q20_6 = models.CharField("Q20_6", max_length=200, blank=True, default=" ")
    q20_7 = models.CharField("Q20_7", max_length=200, blank=True, default=" ")
    q21_1 = models.CharField("Q21_1", max_length=200, blank=True, default=" ")
    q21_2 = models.CharField("Q21_2", max_length=200, blank=True, default=" ")
    q21_3 = models.CharField("Q21_3", max_length=200, blank=True, default=" ")
    q21_4 = models.CharField("Q21_4", max_length=200, blank=True, default=" ")
    q21_5 = models.CharField("Q21_5", max_length=200, blank=True, default=" ")
    q21_6 = models.CharField("Q21_6", max_length=200, blank=True, default=" ")
    q21_7 = models.CharField("Q21_7", max_length=200, blank=True, default=" ")
    q22_1 = models.CharField("Q22_1", max_length=200, blank=True, default=" ")
    q22_2 = models.CharField("Q22_2", max_length=200, blank=True, default=" ")
    q22_3 = models.CharField("Q22_3", max_length=200, blank=True, default=" ")
    q22_4 = models.CharField("Q22_4", max_length=200, blank=True, default=" ")
    q22_5 = models.CharField("Q22_5", max_length=200, blank=True, default=" ")
    q22_6 = models.CharField("Q22_6", max_length=200, blank=True, default=" ")
    q22_7 = models.CharField("Q22_7", max_length=200, blank=True, default=" ")
    q23_1 = models.CharField("Q23_1", max_length=200, blank=True, default=" ")
    q23_2 = models.CharField("Q23_2", max_length=200, blank=True, default=" ")
    q23_3 = models.CharField("Q23_3", max_length=200, blank=True, default=" ")
    q23_4 = models.CharField("Q23_4", max_length=200, blank=True, default=" ")
    q23_5 = models.CharField("Q23_5", max_length=200, blank=True, default=" ")
    q23_6 = models.CharField("Q23_6", max_length=200, blank=True, default=" ")
    q23_7 = models.CharField("Q23_7", max_length=200, blank=True, default=" ")
    q24_1 = models.CharField("Q24_1", max_length=200, blank=True, default=" ")
    q24_2 = models.CharField("Q24_2", max_length=200, blank=True, default=" ")
    q24_3 = models.CharField("Q24_3", max_length=200, blank=True, default=" ")
    q24_4 = models.CharField("Q24_4", max_length=200, blank=True, default=" ")
    q24_5 = models.CharField("Q24_5", max_length=200, blank=True, default=" ")
    q24_6 = models.CharField("Q24_6", max_length=200, blank=True, default=" ")
    q24_7 = models.CharField("Q24_7", max_length=200, blank=True, default=" ")
    q25_1 = models.CharField("Q25_1", max_length=200, blank=True, default=" ")
    q25_2 = models.CharField("Q25_2", max_length=200, blank=True, default=" ")
    q25_3 = models.CharField("Q25_3", max_length=200, blank=True, default=" ")
    q25_4 = models.CharField("Q25_4", max_length=200, blank=True, default=" ")
    q25_5 = models.CharField("Q25_5", max_length=200, blank=True, default=" ")
    q25_6 = models.CharField("Q25_6", max_length=200, blank=True, default=" ")
    q25_7 = models.CharField("Q25_7", max_length=200, blank=True, default=" ")
    q26_1 = models.CharField("Q26_1", max_length=200, blank=True, default=" ")
    q26_2 = models.CharField("Q26_2", max_length=200, blank=True, default=" ")
    q26_3 = models.CharField("Q26_3", max_length=200, blank=True, default=" ")
    q26_4 = models.CharField("Q26_4", max_length=200, blank=True, default=" ")
    q26_5 = models.CharField("Q26_5", max_length=200, blank=True, default=" ")
    q26_6 = models.CharField("Q26_6", max_length=200, blank=True, default=" ")
    q26_7 = models.CharField("Q26_7", max_length=200, blank=True, default=" ")
    q27_1 = models.CharField("Q27_1", max_length=200, blank=True, default=" ")
    q27_2 = models.CharField("Q27_2", max_length=200, blank=True, default=" ")
    q27_3 = models.CharField("Q27_3", max_length=200, blank=True, default=" ")
    q27_4 = models.CharField("Q27_4", max_length=200, blank=True, default=" ")
    q27_5 = models.CharField("Q27_5", max_length=200, blank=True, default=" ")
    q27_6 = models.CharField("Q27_6", max_length=200, blank=True, default=" ")
    q27_7 = models.CharField("Q27_7", max_length=200, blank=True, default=" ")
    q28_1 = models.CharField("Q28_1", max_length=200, blank=True, default=" ")
    q28_2 = models.CharField("Q28_2", max_length=200, blank=True, default=" ")
    q28_3 = models.CharField("Q28_3", max_length=200, blank=True, default=" ")
    q28_4 = models.CharField("Q28_4", max_length=200, blank=True, default=" ")
    q28_5 = models.CharField("Q28_5", max_length=200, blank=True, default=" ")
    q28_6 = models.CharField("Q28_6", max_length=200, blank=True, default=" ")
    q28_7 = models.CharField("Q28_7", max_length=200, blank=True, default=" ")
    q29_1 = models.CharField("Q29_1", max_length=200, blank=True, default=" ")
    q29_2 = models.CharField("Q29_2", max_length=200, blank=True, default=" ")
    q29_3 = models.CharField("Q29_3", max_length=200, blank=True, default=" ")
    q29_4 = models.CharField("Q29_4", max_length=200, blank=True, default=" ")
    q29_5 = models.CharField("Q29_5", max_length=200, blank=True, default=" ")
    q29_6 = models.CharField("Q29_6", max_length=200, blank=True, default=" ")
    q29_7 = models.CharField("Q29_7", max_length=200, blank=True, default=" ")
    q30_1 = models.CharField("Q30_1", max_length=200, blank=True, default=" ")
    q30_2 = models.CharField("Q30_2", max_length=200, blank=True, default=" ")
    q30_3 = models.CharField("Q30_3", max_length=200, blank=True, default=" ")
    q30_4 = models.CharField("Q30_4", max_length=200, blank=True, default=" ")
    q30_5 = models.CharField("Q30_5", max_length=200, blank=True, default=" ")
    q30_6 = models.CharField("Q30_6", max_length=200, blank=True, default=" ")
    q30_7 = models.CharField("Q30_7", max_length=200, blank=True, default=" ")
    q31_1 = models.CharField("Q31_1", max_length=200, blank=True, default=" ")
    q31_2 = models.CharField("Q31_2", max_length=200, blank=True, default=" ")
    q31_3 = models.CharField("Q31_3", max_length=200, blank=True, default=" ")
    q31_4 = models.CharField("Q31_4", max_length=200, blank=True, default=" ")
    q31_5 = models.CharField("Q31_5", max_length=200, blank=True, default=" ")
    q31_6 = models.CharField("Q31_6", max_length=200, blank=True, default=" ")
    q31_7 = models.CharField("Q31_7", max_length=200, blank=True, default=" ")
    q32_1 = models.CharField("Q32_1", max_length=200, blank=True, default=" ")
    q32_2 = models.CharField("Q32_2", max_length=200, blank=True, default=" ")
    q32_3 = models.CharField("Q32_3", max_length=200, blank=True, default=" ")
    q32_4 = models.CharField("Q32_4", max_length=200, blank=True, default=" ")
    q32_5 = models.CharField("Q32_5", max_length=200, blank=True, default=" ")
    q32_6 = models.CharField("Q32_6", max_length=200, blank=True, default=" ")
    q32_7 = models.CharField("Q32_7", max_length=200, blank=True, default=" ")
    q33_1 = models.CharField("Q33_1", max_length=200, blank=True, default=" ")
    q33_2 = models.CharField("Q33_2", max_length=200, blank=True, default=" ")
    q33_3 = models.CharField("Q33_3", max_length=200, blank=True, default=" ")
    q33_4 = models.CharField("Q33_4", max_length=200, blank=True, default=" ")
    q33_5 = models.CharField("Q33_5", max_length=200, blank=True, default=" ")
    q33_6 = models.CharField("Q33_6", max_length=200, blank=True, default=" ")
    q33_7 = models.CharField("Q33_7", max_length=200, blank=True, default=" ")
    q34_1 = models.CharField("Q34_1", max_length=200, blank=True, default=" ")
    q34_2 = models.CharField("Q34_2", max_length=200, blank=True, default=" ")
    q34_3 = models.CharField("Q34_3", max_length=200, blank=True, default=" ")
    q34_4 = models.CharField("Q34_4", max_length=200, blank=True, default=" ")
    q34_5 = models.CharField("Q34_5", max_length=200, blank=True, default=" ")
    q34_6 = models.CharField("Q34_6", max_length=200, blank=True, default=" ")
    q34_7 = models.CharField("Q34_7", max_length=200, blank=True, default=" ")
    q35_1 = models.CharField("Q35_1", max_length=200, blank=True, default=" ")
    q35_2 = models.CharField("Q35_2", max_length=200, blank=True, default=" ")
    q35_3 = models.CharField("Q35_3", max_length=200, blank=True, default=" ")
    q35_4 = models.CharField("Q35_4", max_length=200, blank=True, default=" ")
    q35_5 = models.CharField("Q35_5", max_length=200, blank=True, default=" ")
    q35_6 = models.CharField("Q35_6", max_length=200, blank=True, default=" ")
    q35_7 = models.CharField("Q35_7", max_length=200, blank=True, default=" ")
    q36_1 = models.CharField("Q36_1", max_length=200, blank=True, default=" ")
    q36_2 = models.CharField("Q36_2", max_length=200, blank=True, default=" ")
    q36_3 = models.CharField("Q36_3", max_length=200, blank=True, default=" ")
    q36_4 = models.CharField("Q36_4", max_length=200, blank=True, default=" ")
    q36_5 = models.CharField("Q36_5", max_length=200, blank=True, default=" ")
    q36_6 = models.CharField("Q36_6", max_length=200, blank=True, default=" ")
    q36_7 = models.CharField("Q36_7", max_length=200, blank=True, default=" ")
    q37_1 = models.CharField("Q37_1", max_length=200, blank=True, default=" ")
    q37_2 = models.CharField("Q37_2", max_length=200, blank=True, default=" ")
    q37_3 = models.CharField("Q37_3", max_length=200, blank=True, default=" ")
    q37_4 = models.CharField("Q37_4", max_length=200, blank=True, default=" ")
    q37_5 = models.CharField("Q37_5", max_length=200, blank=True, default=" ")
    q37_6 = models.CharField("Q37_6", max_length=200, blank=True, default=" ")
    q37_7 = models.CharField("Q37_7", max_length=200, blank=True, default=" ")
    q38_1 = models.CharField("Q38_1", max_length=200, blank=True, default=" ")
    q38_2 = models.CharField("Q38_2", max_length=200, blank=True, default=" ")
    q38_3 = models.CharField("Q38_3", max_length=200, blank=True, default=" ")
    q38_4 = models.CharField("Q38_4", max_length=200, blank=True, default=" ")
    q38_5 = models.CharField("Q38_5", max_length=200, blank=True, default=" ")
    q38_6 = models.CharField("Q38_6", max_length=200, blank=True, default=" ")
    q38_7 = models.CharField("Q38_7", max_length=200, blank=True, default=" ")
    q39_1 = models.CharField("Q39_1", max_length=200, blank=True, default=" ")
    q39_2 = models.CharField("Q39_2", max_length=200, blank=True, default=" ")
    q39_3 = models.CharField("Q39_3", max_length=200, blank=True, default=" ")
    q39_4 = models.CharField("Q39_4", max_length=200, blank=True, default=" ")
    q39_5 = models.CharField("Q39_5", max_length=200, blank=True, default=" ")
    q39_6 = models.CharField("Q39_6", max_length=200, blank=True, default=" ")
    q39_7 = models.CharField("Q39_7", max_length=200, blank=True, default=" ")
    q40_1 = models.CharField("Q40_1", max_length=200, blank=True, default=" ")
    q40_2 = models.CharField("Q40_2", max_length=200, blank=True, default=" ")
    q40_3 = models.CharField("Q40_3", max_length=200, blank=True, default=" ")
    q40_4 = models.CharField("Q40_4", max_length=200, blank=True, default=" ")
    q40_5 = models.CharField("Q40_5", max_length=200, blank=True, default=" ")
    q40_6 = models.CharField("Q40_6", max_length=200, blank=True, default=" ")
    q40_7 = models.CharField("Q40_7", max_length=200, blank=True, default=" ")
    q41_1 = models.CharField("Q41_1", max_length=200, blank=True, default=" ")
    q41_2 = models.CharField("Q41_2", max_length=200, blank=True, default=" ")
    q41_3 = models.CharField("Q41_3", max_length=200, blank=True, default=" ")
    q41_4 = models.CharField("Q41_4", max_length=200, blank=True, default=" ")
    q41_5 = models.CharField("Q41_5", max_length=200, blank=True, default=" ")
    q41_6 = models.CharField("Q41_6", max_length=200, blank=True, default=" ")
    q41_7 = models.CharField("Q41_7", max_length=200, blank=True, default=" ")
    q42_1 = models.CharField("Q42_1", max_length=200, blank=True, default=" ")
    q42_2 = models.CharField("Q42_2", max_length=200, blank=True, default=" ")
    q42_3 = models.CharField("Q42_3", max_length=200, blank=True, default=" ")
    q42_4 = models.CharField("Q42_4", max_length=200, blank=True, default=" ")
    q42_5 = models.CharField("Q42_5", max_length=200, blank=True, default=" ")
    q42_6 = models.CharField("Q42_6", max_length=200, blank=True, default=" ")
    q42_7 = models.CharField("Q42_7", max_length=200, blank=True, default=" ")
    q43_1 = models.CharField("Q43_1", max_length=200, blank=True, default=" ")
    q43_2 = models.CharField("Q43_2", max_length=200, blank=True, default=" ")
    q43_3 = models.CharField("Q43_3", max_length=200, blank=True, default=" ")
    q43_4 = models.CharField("Q43_4", max_length=200, blank=True, default=" ")
    q43_5 = models.CharField("Q43_5", max_length=200, blank=True, default=" ")
    q43_6 = models.CharField("Q43_6", max_length=200, blank=True, default=" ")
    q43_7 = models.CharField("Q43_7", max_length=200, blank=True, default=" ")
    q44_1 = models.CharField("Q44_1", max_length=200, blank=True, default=" ")
    q44_2 = models.CharField("Q44_2", max_length=200, blank=True, default=" ")
    q44_3 = models.CharField("Q44_3", max_length=200, blank=True, default=" ")
    q44_4 = models.CharField("Q44_4", max_length=200, blank=True, default=" ")
    q44_5 = models.CharField("Q44_5", max_length=200, blank=True, default=" ")
    q44_6 = models.CharField("Q44_6", max_length=200, blank=True, default=" ")
    q44_7 = models.CharField("Q44_7", max_length=200, blank=True, default=" ")
    q45_1 = models.CharField("Q45_1", max_length=200, blank=True, default=" ")
    q45_2 = models.CharField("Q45_2", max_length=200, blank=True, default=" ")
    q45_3 = models.CharField("Q45_3", max_length=200, blank=True, default=" ")
    q45_4 = models.CharField("Q45_4", max_length=200, blank=True, default=" ")
    q45_5 = models.CharField("Q45_5", max_length=200, blank=True, default=" ")
    q45_6 = models.CharField("Q45_6", max_length=200, blank=True, default=" ")
    q45_7 = models.CharField("Q45_7", max_length=200, blank=True, default=" ")
    q46_1 = models.CharField("Q46_1", max_length=200, blank=True, default=" ")
    q46_2 = models.CharField("Q46_2", max_length=200, blank=True, default=" ")
    q46_3 = models.CharField("Q46_3", max_length=200, blank=True, default=" ")
    q46_4 = models.CharField("Q46_4", max_length=200, blank=True, default=" ")
    q46_5 = models.CharField("Q46_5", max_length=200, blank=True, default=" ")
    q46_6 = models.CharField("Q46_6", max_length=200, blank=True, default=" ")
    q46_7 = models.CharField("Q46_7", max_length=200, blank=True, default=" ")
    q47_1 = models.CharField("Q47_1", max_length=200, blank=True, default=" ")
    q47_2 = models.CharField("Q47_2", max_length=200, blank=True, default=" ")
    q47_3 = models.CharField("Q47_3", max_length=200, blank=True, default=" ")
    q47_4 = models.CharField("Q47_4", max_length=200, blank=True, default=" ")
    q47_5 = models.CharField("Q47_5", max_length=200, blank=True, default=" ")
    q47_6 = models.CharField("Q47_6", max_length=200, blank=True, default=" ")
    q47_7 = models.CharField("Q47_7", max_length=200, blank=True, default=" ")
    q48_1 = models.CharField("Q48_1", max_length=200, blank=True, default=" ")
    q48_2 = models.CharField("Q48_2", max_length=200, blank=True, default=" ")
    q48_3 = models.CharField("Q48_3", max_length=200, blank=True, default=" ")
    q48_4 = models.CharField("Q48_4", max_length=200, blank=True, default=" ")
    q48_5 = models.CharField("Q48_5", max_length=200, blank=True, default=" ")
    q48_6 = models.CharField("Q48_6", max_length=200, blank=True, default=" ")
    q48_7 = models.CharField("Q48_7", max_length=200, blank=True, default=" ")
    q49_1 = models.CharField("Q49_1", max_length=200, blank=True, default=" ")
    q49_2 = models.CharField("Q49_2", max_length=200, blank=True, default=" ")
    q49_3 = models.CharField("Q49_3", max_length=200, blank=True, default=" ")
    q49_4 = models.CharField("Q49_4", max_length=200, blank=True, default=" ")
    q49_5 = models.CharField("Q49_5", max_length=200, blank=True, default=" ")
    q49_6 = models.CharField("Q49_6", max_length=200, blank=True, default=" ")
    q49_7 = models.CharField("Q49_7", max_length=200, blank=True, default=" ")
    q50_1 = models.CharField("Q50_1", max_length=200, blank=True, default=" ")
    q50_2 = models.CharField("Q50_2", max_length=200, blank=True, default=" ")
    q50_3 = models.CharField("Q50_3", max_length=200, blank=True, default=" ")
    q50_4 = models.CharField("Q50_4", max_length=200, blank=True, default=" ")
    q50_5 = models.CharField("Q50_5", max_length=200, blank=True, default=" ")
    q50_6 = models.CharField("Q50_6", max_length=200, blank=True, default=" ")
    q50_7 = models.CharField("Q50_7", max_length=200, blank=True, default=" ")
    q51_1 = models.CharField("Q51_1", max_length=200, blank=True, default=" ")
    q51_2 = models.CharField("Q51_2", max_length=200, blank=True, default=" ")
    q51_3 = models.CharField("Q51_3", max_length=200, blank=True, default=" ")
    q51_4 = models.CharField("Q51_4", max_length=200, blank=True, default=" ")
    q51_5 = models.CharField("Q51_5", max_length=200, blank=True, default=" ")
    q51_6 = models.CharField("Q51_6", max_length=200, blank=True, default=" ")
    q51_7 = models.CharField("Q51_7", max_length=200, blank=True, default=" ")
    q52_1 = models.CharField("Q52_1", max_length=200, blank=True, default=" ")
    q52_2 = models.CharField("Q52_2", max_length=200, blank=True, default=" ")
    q52_3 = models.CharField("Q52_3", max_length=200, blank=True, default=" ")
    q52_4 = models.CharField("Q52_4", max_length=200, blank=True, default=" ")
    q52_5 = models.CharField("Q52_5", max_length=200, blank=True, default=" ")
    q52_6 = models.CharField("Q52_6", max_length=200, blank=True, default=" ")
    q52_7 = models.CharField("Q52_7", max_length=200, blank=True, default=" ")
    q53_1 = models.CharField("Q53_1", max_length=200, blank=True, default=" ")
    q53_2 = models.CharField("Q53_2", max_length=200, blank=True, default=" ")
    q53_3 = models.CharField("Q53_3", max_length=200, blank=True, default=" ")
    q53_4 = models.CharField("Q53_4", max_length=200, blank=True, default=" ")
    q53_5 = models.CharField("Q53_5", max_length=200, blank=True, default=" ")
    q53_6 = models.CharField("Q53_6", max_length=200, blank=True, default=" ")
    q53_7 = models.CharField("Q53_7", max_length=200, blank=True, default=" ")
    q54_1 = models.CharField("Q54_1", max_length=200, blank=True, default=" ")
    q54_2 = models.CharField("Q54_2", max_length=200, blank=True, default=" ")
    q54_3 = models.CharField("Q54_3", max_length=200, blank=True, default=" ")
    q54_4 = models.CharField("Q54_4", max_length=200, blank=True, default=" ")
    q54_5 = models.CharField("Q54_5", max_length=200, blank=True, default=" ")
    q54_6 = models.CharField("Q54_6", max_length=200, blank=True, default=" ")
    q54_7 = models.CharField("Q54_7", max_length=200, blank=True, default=" ")
    q55_1 = models.CharField("Q55_1", max_length=200, blank=True, default=" ")
    q55_2 = models.CharField("Q55_2", max_length=200, blank=True, default=" ")
    q55_3 = models.CharField("Q55_3", max_length=200, blank=True, default=" ")
    q55_4 = models.CharField("Q55_4", max_length=200, blank=True, default=" ")
    q55_5 = models.CharField("Q55_5", max_length=200, blank=True, default=" ")
    q55_6 = models.CharField("Q55_6", max_length=200, blank=True, default=" ")
    q55_7 = models.CharField("Q55_7", max_length=200, blank=True, default=" ")
    q56_1 = models.CharField("Q56_1", max_length=200, blank=True, default=" ")
    q56_2 = models.CharField("Q56_2", max_length=200, blank=True, default=" ")
    q56_3 = models.CharField("Q56_3", max_length=200, blank=True, default=" ")
    q56_4 = models.CharField("Q56_4", max_length=200, blank=True, default=" ")
    q56_5 = models.CharField("Q56_5", max_length=200, blank=True, default=" ")
    q56_6 = models.CharField("Q56_6", max_length=200, blank=True, default=" ")
    q56_7 = models.CharField("Q56_7", max_length=200, blank=True, default=" ")
    q57_1 = models.CharField("Q57_1", max_length=200, blank=True, default=" ")
    q57_2 = models.CharField("Q57_2", max_length=200, blank=True, default=" ")
    q57_3 = models.CharField("Q57_3", max_length=200, blank=True, default=" ")
    q57_4 = models.CharField("Q57_4", max_length=200, blank=True, default=" ")
    q57_5 = models.CharField("Q57_5", max_length=200, blank=True, default=" ")
    q57_6 = models.CharField("Q57_6", max_length=200, blank=True, default=" ")
    q57_7 = models.CharField("Q57_7", max_length=200, blank=True, default=" ")
    q58_1 = models.CharField("Q58_1", max_length=200, blank=True, default=" ")
    q58_2 = models.CharField("Q58_2", max_length=200, blank=True, default=" ")
    q58_3 = models.CharField("Q58_3", max_length=200, blank=True, default=" ")
    q58_4 = models.CharField("Q58_4", max_length=200, blank=True, default=" ")
    q58_5 = models.CharField("Q58_5", max_length=200, blank=True, default=" ")
    q58_6 = models.CharField("Q58_6", max_length=200, blank=True, default=" ")
    q58_7 = models.CharField("Q58_7", max_length=200, blank=True, default=" ")
    q59_1 = models.CharField("Q59_1", max_length=200, blank=True, default=" ")
    q59_2 = models.CharField("Q59_2", max_length=200, blank=True, default=" ")
    q59_3 = models.CharField("Q59_3", max_length=200, blank=True, default=" ")
    q59_4 = models.CharField("Q59_4", max_length=200, blank=True, default=" ")
    q59_5 = models.CharField("Q59_5", max_length=200, blank=True, default=" ")
    q59_6 = models.CharField("Q59_6", max_length=200, blank=True, default=" ")
    q59_7 = models.CharField("Q59_7", max_length=200, blank=True, default=" ")
    q60_1 = models.CharField("Q60_1", max_length=200, blank=True, default=" ")
    q60_2 = models.CharField("Q60_2", max_length=200, blank=True, default=" ")
    q60_3 = models.CharField("Q60_3", max_length=200, blank=True, default=" ")
    q60_4 = models.CharField("Q60_4", max_length=200, blank=True, default=" ")
    q60_5 = models.CharField("Q60_5", max_length=200, blank=True, default=" ")
    q60_6 = models.CharField("Q60_6", max_length=200, blank=True, default=" ")
    q60_7 = models.CharField("Q60_7", max_length=200, blank=True, default=" ")
    q61_1 = models.CharField("Q61_1", max_length=200, blank=True, default=" ")
    q61_2 = models.CharField("Q61_2", max_length=200, blank=True, default=" ")
    q61_3 = models.CharField("Q61_3", max_length=200, blank=True, default=" ")
    q61_4 = models.CharField("Q61_4", max_length=200, blank=True, default=" ")
    q61_5 = models.CharField("Q61_5", max_length=200, blank=True, default=" ")
    q61_6 = models.CharField("Q61_6", max_length=200, blank=True, default=" ")
    q61_7 = models.CharField("Q61_7", max_length=200, blank=True, default=" ")
    q62_1 = models.CharField("Q62_1", max_length=200, blank=True, default=" ")
    q62_2 = models.CharField("Q62_2", max_length=200, blank=True, default=" ")
    q62_3 = models.CharField("Q62_3", max_length=200, blank=True, default=" ")
    q62_4 = models.CharField("Q62_4", max_length=200, blank=True, default=" ")
    q62_5 = models.CharField("Q62_5", max_length=200, blank=True, default=" ")
    q62_6 = models.CharField("Q62_6", max_length=200, blank=True, default=" ")
    q62_7 = models.CharField("Q62_7", max_length=200, blank=True, default=" ")
    q63_1 = models.CharField("Q63_1", max_length=200, blank=True, default=" ")
    q63_2 = models.CharField("Q63_2", max_length=200, blank=True, default=" ")
    q63_3 = models.CharField("Q63_3", max_length=200, blank=True, default=" ")
    q63_4 = models.CharField("Q63_4", max_length=200, blank=True, default=" ")
    q63_5 = models.CharField("Q63_5", max_length=200, blank=True, default=" ")
    q63_6 = models.CharField("Q63_6", max_length=200, blank=True, default=" ")
    q63_7 = models.CharField("Q63_7", max_length=200, blank=True, default=" ")
    q64_1 = models.CharField("Q64_1", max_length=200, blank=True, default=" ")
    q64_2 = models.CharField("Q64_2", max_length=200, blank=True, default=" ")
    q64_3 = models.CharField("Q64_3", max_length=200, blank=True, default=" ")
    q64_4 = models.CharField("Q64_4", max_length=200, blank=True, default=" ")
    q64_5 = models.CharField("Q64_5", max_length=200, blank=True, default=" ")
    q64_6 = models.CharField("Q64_6", max_length=200, blank=True, default=" ")
    q64_7 = models.CharField("Q64_7", max_length=200, blank=True, default=" ")
    q65_1 = models.CharField("Q65_1", max_length=200, blank=True, default=" ")
    q65_2 = models.CharField("Q65_2", max_length=200, blank=True, default=" ")
    q65_3 = models.CharField("Q65_3", max_length=200, blank=True, default=" ")
    q65_4 = models.CharField("Q65_4", max_length=200, blank=True, default=" ")
    q65_5 = models.CharField("Q65_5", max_length=200, blank=True, default=" ")
    q65_6 = models.CharField("Q65_6", max_length=200, blank=True, default=" ")
    q65_7 = models.CharField("Q65_7", max_length=200, blank=True, default=" ")
    q66_1 = models.CharField("Q66_1", max_length=200, blank=True, default=" ")
    q66_2 = models.CharField("Q66_2", max_length=200, blank=True, default=" ")
    q66_3 = models.CharField("Q66_3", max_length=200, blank=True, default=" ")
    q66_4 = models.CharField("Q66_4", max_length=200, blank=True, default=" ")
    q66_5 = models.CharField("Q66_5", max_length=200, blank=True, default=" ")
    q66_6 = models.CharField("Q66_6", max_length=200, blank=True, default=" ")
    q66_7 = models.CharField("Q66_7", max_length=200, blank=True, default=" ")
    q67_1 = models.CharField("Q67_1", max_length=200, blank=True, default=" ")
    q67_2 = models.CharField("Q67_2", max_length=200, blank=True, default=" ")
    q67_3 = models.CharField("Q67_3", max_length=200, blank=True, default=" ")
    q67_4 = models.CharField("Q67_4", max_length=200, blank=True, default=" ")
    q67_5 = models.CharField("Q67_5", max_length=200, blank=True, default=" ")
    q67_6 = models.CharField("Q67_6", max_length=200, blank=True, default=" ")
    q67_7 = models.CharField("Q67_7", max_length=200, blank=True, default=" ")
    q68_1 = models.CharField("Q68_1", max_length=200, blank=True, default=" ")
    q68_2 = models.CharField("Q68_2", max_length=200, blank=True, default=" ")
    q68_3 = models.CharField("Q68_3", max_length=200, blank=True, default=" ")
    q68_4 = models.CharField("Q68_4", max_length=200, blank=True, default=" ")
    q68_5 = models.CharField("Q68_5", max_length=200, blank=True, default=" ")
    q68_6 = models.CharField("Q68_6", max_length=200, blank=True, default=" ")
    q68_7 = models.CharField("Q68_7", max_length=200, blank=True, default=" ")
    q69_1 = models.CharField("Q69_1", max_length=200, blank=True, default=" ")
    q69_2 = models.CharField("Q69_2", max_length=200, blank=True, default=" ")
    q69_3 = models.CharField("Q69_3", max_length=200, blank=True, default=" ")
    q69_4 = models.CharField("Q69_4", max_length=200, blank=True, default=" ")
    q69_5 = models.CharField("Q69_5", max_length=200, blank=True, default=" ")
    q69_6 = models.CharField("Q69_6", max_length=200, blank=True, default=" ")
    q69_7 = models.CharField("Q69_7", max_length=200, blank=True, default=" ")
    q70_1 = models.CharField("Q70_1", max_length=200, blank=True, default=" ")
    q70_2 = models.CharField("Q70_2", max_length=200, blank=True, default=" ")
    q70_3 = models.CharField("Q70_3", max_length=200, blank=True, default=" ")
    q70_4 = models.CharField("Q70_4", max_length=200, blank=True, default=" ")
    q70_5 = models.CharField("Q70_5", max_length=200, blank=True, default=" ")
    q70_6 = models.CharField("Q70_6", max_length=200, blank=True, default=" ")
    q70_7 = models.CharField("Q70_7", max_length=200, blank=True, default=" ")
    q71_1 = models.CharField("Q71_1", max_length=200, blank=True, default=" ")
    q71_2 = models.CharField("Q71_2", max_length=200, blank=True, default=" ")
    q71_3 = models.CharField("Q71_3", max_length=200, blank=True, default=" ")
    q71_4 = models.CharField("Q71_4", max_length=200, blank=True, default=" ")
    q71_5 = models.CharField("Q71_5", max_length=200, blank=True, default=" ")
    q71_6 = models.CharField("Q71_6", max_length=200, blank=True, default=" ")
    q71_7 = models.CharField("Q71_7", max_length=200, blank=True, default=" ")
    q72_1 = models.CharField("Q72_1", max_length=200, blank=True, default=" ")
    q72_2 = models.CharField("Q72_2", max_length=200, blank=True, default=" ")
    q72_3 = models.CharField("Q72_3", max_length=200, blank=True, default=" ")
    q72_4 = models.CharField("Q72_4", max_length=200, blank=True, default=" ")
    q72_5 = models.CharField("Q72_5", max_length=200, blank=True, default=" ")
    q72_6 = models.CharField("Q72_6", max_length=200, blank=True, default=" ")
    q72_7 = models.CharField("Q72_7", max_length=200, blank=True, default=" ")
    q73_1 = models.CharField("Q73_1", max_length=200, blank=True, default=" ")
    q73_2 = models.CharField("Q73_2", max_length=200, blank=True, default=" ")
    q73_3 = models.CharField("Q73_3", max_length=200, blank=True, default=" ")
    q73_4 = models.CharField("Q73_4", max_length=200, blank=True, default=" ")
    q73_5 = models.CharField("Q73_5", max_length=200, blank=True, default=" ")
    q73_6 = models.CharField("Q73_6", max_length=200, blank=True, default=" ")
    q73_7 = models.CharField("Q73_7", max_length=200, blank=True, default=" ")
    q74_1 = models.CharField("Q74_1", max_length=200, blank=True, default=" ")
    q74_2 = models.CharField("Q74_2", max_length=200, blank=True, default=" ")
    q74_3 = models.CharField("Q74_3", max_length=200, blank=True, default=" ")
    q74_4 = models.CharField("Q74_4", max_length=200, blank=True, default=" ")
    q74_5 = models.CharField("Q74_5", max_length=200, blank=True, default=" ")
    q74_6 = models.CharField("Q74_6", max_length=200, blank=True, default=" ")
    q74_7 = models.CharField("Q74_7", max_length=200, blank=True, default=" ")
    q75_1 = models.CharField("Q75_1", max_length=200, blank=True, default=" ")
    q75_2 = models.CharField("Q75_2", max_length=200, blank=True, default=" ")
    q75_3 = models.CharField("Q75_3", max_length=200, blank=True, default=" ")
    q75_4 = models.CharField("Q75_4", max_length=200, blank=True, default=" ")
    q75_5 = models.CharField("Q75_5", max_length=200, blank=True, default=" ")
    q75_6 = models.CharField("Q75_6", max_length=200, blank=True, default=" ")
    q75_7 = models.CharField("Q75_7", max_length=200, blank=True, default=" ")
    q76_1 = models.CharField("Q76_1", max_length=200, blank=True, default=" ")
    q76_2 = models.CharField("Q76_2", max_length=200, blank=True, default=" ")
    q76_3 = models.CharField("Q76_3", max_length=200, blank=True, default=" ")
    q76_4 = models.CharField("Q76_4", max_length=200, blank=True, default=" ")
    q76_5 = models.CharField("Q76_5", max_length=200, blank=True, default=" ")
    q76_6 = models.CharField("Q76_6", max_length=200, blank=True, default=" ")
    q76_7 = models.CharField("Q76_7", max_length=200, blank=True, default=" ")
    q77_1 = models.CharField("Q77_1", max_length=200, blank=True, default=" ")
    q77_2 = models.CharField("Q77_2", max_length=200, blank=True, default=" ")
    q77_3 = models.CharField("Q77_3", max_length=200, blank=True, default=" ")
    q77_4 = models.CharField("Q77_4", max_length=200, blank=True, default=" ")
    q77_5 = models.CharField("Q77_5", max_length=200, blank=True, default=" ")
    q77_6 = models.CharField("Q77_6", max_length=200, blank=True, default=" ")
    q77_7 = models.CharField("Q77_7", max_length=200, blank=True, default=" ")
    q78_1 = models.CharField("Q78_1", max_length=200, blank=True, default=" ")
    q78_2 = models.CharField("Q78_2", max_length=200, blank=True, default=" ")
    q78_3 = models.CharField("Q78_3", max_length=200, blank=True, default=" ")
    q78_4 = models.CharField("Q78_4", max_length=200, blank=True, default=" ")
    q78_5 = models.CharField("Q78_5", max_length=200, blank=True, default=" ")
    q78_6 = models.CharField("Q78_6", max_length=200, blank=True, default=" ")
    q78_7 = models.CharField("Q78_7", max_length=200, blank=True, default=" ")
    q79_1 = models.CharField("Q79_1", max_length=200, blank=True, default=" ")
    q79_2 = models.CharField("Q79_2", max_length=200, blank=True, default=" ")
    q79_3 = models.CharField("Q79_3", max_length=200, blank=True, default=" ")
    q79_4 = models.CharField("Q79_4", max_length=200, blank=True, default=" ")
    q79_5 = models.CharField("Q79_5", max_length=200, blank=True, default=" ")
    q79_6 = models.CharField("Q79_6", max_length=200, blank=True, default=" ")
    q79_7 = models.CharField("Q79_7", max_length=200, blank=True, default=" ")
    q80_1 = models.CharField("Q80_1", max_length=200, blank=True, default=" ")
    q80_2 = models.CharField("Q80_2", max_length=200, blank=True, default=" ")
    q80_3 = models.CharField("Q80_3", max_length=200, blank=True, default=" ")
    q80_4 = models.CharField("Q80_4", max_length=200, blank=True, default=" ")
    q80_5 = models.CharField("Q80_5", max_length=200, blank=True, default=" ")
    q80_6 = models.CharField("Q80_6", max_length=200, blank=True, default=" ")
    q80_7 = models.CharField("Q80_7", max_length=200, blank=True, default=" ")
    q81_1 = models.CharField("Q81_1", max_length=200, blank=True, default=" ")
    q81_2 = models.CharField("Q81_2", max_length=200, blank=True, default=" ")
    q81_3 = models.CharField("Q81_3", max_length=200, blank=True, default=" ")
    q81_4 = models.CharField("Q81_4", max_length=200, blank=True, default=" ")
    q81_5 = models.CharField("Q81_5", max_length=200, blank=True, default=" ")
    q81_6 = models.CharField("Q81_6", max_length=200, blank=True, default=" ")
    q81_7 = models.CharField("Q81_7", max_length=200, blank=True, default=" ")
    q82_1 = models.CharField("Q82_1", max_length=200, blank=True, default=" ")
    q82_2 = models.CharField("Q82_2", max_length=200, blank=True, default=" ")
    q82_3 = models.CharField("Q82_3", max_length=200, blank=True, default=" ")
    q82_4 = models.CharField("Q82_4", max_length=200, blank=True, default=" ")
    q82_5 = models.CharField("Q82_5", max_length=200, blank=True, default=" ")
    q82_6 = models.CharField("Q82_6", max_length=200, blank=True, default=" ")
    q82_7 = models.CharField("Q82_7", max_length=200, blank=True, default=" ")
    q83_1 = models.CharField("Q83_1", max_length=200, blank=True, default=" ")
    q83_2 = models.CharField("Q83_2", max_length=200, blank=True, default=" ")
    q83_3 = models.CharField("Q83_3", max_length=200, blank=True, default=" ")
    q83_4 = models.CharField("Q83_4", max_length=200, blank=True, default=" ")
    q83_5 = models.CharField("Q83_5", max_length=200, blank=True, default=" ")
    q83_6 = models.CharField("Q83_6", max_length=200, blank=True, default=" ")
    q83_7 = models.CharField("Q83_7", max_length=200, blank=True, default=" ")
    q84_1 = models.CharField("Q84_1", max_length=200, blank=True, default=" ")
    q84_2 = models.CharField("Q84_2", max_length=200, blank=True, default=" ")
    q84_3 = models.CharField("Q84_3", max_length=200, blank=True, default=" ")
    q84_4 = models.CharField("Q84_4", max_length=200, blank=True, default=" ")
    q84_5 = models.CharField("Q84_5", max_length=200, blank=True, default=" ")
    q84_6 = models.CharField("Q84_6", max_length=200, blank=True, default=" ")
    q84_7 = models.CharField("Q84_7", max_length=200, blank=True, default=" ")
    q89_1 = models.CharField("Q89_1", max_length=200, blank=True, default=" ")
    q89_2 = models.CharField("Q89_2", max_length=200, blank=True, default=" ")
    q89_3 = models.CharField("Q89_3", max_length=200, blank=True, default=" ")
    q89_4 = models.CharField("Q89_4", max_length=200, blank=True, default=" ")
    q89_5 = models.CharField("Q89_5", max_length=200, blank=True, default=" ")
    q89_6 = models.CharField("Q89_6", max_length=200, blank=True, default=" ")
    q89_7 = models.CharField("Q89_7", max_length=200, blank=True, default=" ")
    q90_1 = models.CharField("Q90_1", max_length=200, blank=True, default=" ")
    q90_2 = models.CharField("Q90_2", max_length=200, blank=True, default=" ")
    q90_3 = models.CharField("Q90_3", max_length=200, blank=True, default=" ")
    q90_4 = models.CharField("Q90_4", max_length=200, blank=True, default=" ")
    q90_5 = models.CharField("Q90_5", max_length=200, blank=True, default=" ")
    q90_6 = models.CharField("Q90_6", max_length=200, blank=True, default=" ")
    q90_7 = models.CharField("Q90_7", max_length=200, blank=True, default=" ")
    q91_1 = models.CharField("Q91_1", max_length=200, blank=True, default=" ")
    q91_2 = models.CharField("Q91_2", max_length=200, blank=True, default=" ")
    q91_3 = models.CharField("Q91_3", max_length=200, blank=True, default=" ")
    q91_4 = models.CharField("Q91_4", max_length=200, blank=True, default=" ")
    q91_5 = models.CharField("Q91_5", max_length=200, blank=True, default=" ")
    q91_6 = models.CharField("Q91_6", max_length=200, blank=True, default=" ")
    q91_7 = models.CharField("Q91_7", max_length=200, blank=True, default=" ")
    q92_1 = models.CharField("Q92_1", max_length=200, blank=True, default=" ")
    q92_2 = models.CharField("Q92_2", max_length=200, blank=True, default=" ")
    q92_3 = models.CharField("Q92_3", max_length=200, blank=True, default=" ")
    q92_4 = models.CharField("Q92_4", max_length=200, blank=True, default=" ")
    q92_5 = models.CharField("Q92_5", max_length=200, blank=True, default=" ")
    q92_6 = models.CharField("Q92_6", max_length=200, blank=True, default=" ")
    q92_7 = models.CharField("Q92_7", max_length=200, blank=True, default=" ")
    q93_1 = models.CharField("Q93_1", max_length=200, blank=True, default=" ")
    q93_2 = models.CharField("Q93_2", max_length=200, blank=True, default=" ")
    q93_3 = models.CharField("Q93_3", max_length=200, blank=True, default=" ")
    q93_4 = models.CharField("Q93_4", max_length=200, blank=True, default=" ")
    q93_5 = models.CharField("Q93_5", max_length=200, blank=True, default=" ")
    q93_6 = models.CharField("Q93_6", max_length=200, blank=True, default=" ")
    q93_7 = models.CharField("Q93_7", max_length=200, blank=True, default=" ")
    q94_1 = models.CharField("Q94_1", max_length=200, blank=True, default=" ")
    q94_2 = models.CharField("Q94_2", max_length=200, blank=True, default=" ")
    q94_3 = models.CharField("Q94_3", max_length=200, blank=True, default=" ")
    q94_4 = models.CharField("Q94_4", max_length=200, blank=True, default=" ")
    q94_5 = models.CharField("Q94_5", max_length=200, blank=True, default=" ")
    q94_6 = models.CharField("Q94_6", max_length=200, blank=True, default=" ")
    q94_7 = models.CharField("Q94_7", max_length=200, blank=True, default=" ")
    q95_1 = models.CharField("Q95_1", max_length=200, blank=True, default=" ")
    q95_2 = models.CharField("Q95_2", max_length=200, blank=True, default=" ")
    q95_3 = models.CharField("Q95_3", max_length=200, blank=True, default=" ")
    q95_4 = models.CharField("Q95_4", max_length=200, blank=True, default=" ")
    q95_5 = models.CharField("Q95_5", max_length=200, blank=True, default=" ")
    q95_6 = models.CharField("Q95_6", max_length=200, blank=True, default=" ")
    q95_7 = models.CharField("Q95_7", max_length=200, blank=True, default=" ")
    q96_1 = models.CharField("Q96_1", max_length=200, blank=True, default=" ")
    q96_2 = models.CharField("Q96_2", max_length=200, blank=True, default=" ")
    q96_3 = models.CharField("Q96_3", max_length=200, blank=True, default=" ")
    q96_4 = models.CharField("Q96_4", max_length=200, blank=True, default=" ")
    q96_5 = models.CharField("Q96_5", max_length=200, blank=True, default=" ")
    q96_6 = models.CharField("Q96_6", max_length=200, blank=True, default=" ")
    q96_7 = models.CharField("Q96_7", max_length=200, blank=True, default=" ")
    q97_1 = models.CharField("Q97_1", max_length=200, blank=True, default=" ")
    q97_2 = models.CharField("Q97_2", max_length=200, blank=True, default=" ")
    q97_3 = models.CharField("Q97_3", max_length=200, blank=True, default=" ")
    q97_4 = models.CharField("Q97_4", max_length=200, blank=True, default=" ")
    q97_5 = models.CharField("Q97_5", max_length=200, blank=True, default=" ")
    q97_6 = models.CharField("Q97_6", max_length=200, blank=True, default=" ")
    q97_7 = models.CharField("Q97_7", max_length=200, blank=True, default=" ")
    q98_1 = models.CharField("Q98_1", max_length=200, blank=True, default=" ")
    q98_2 = models.CharField("Q98_2", max_length=200, blank=True, default=" ")
    q98_3 = models.CharField("Q98_3", max_length=200, blank=True, default=" ")
    q98_4 = models.CharField("Q98_4", max_length=200, blank=True, default=" ")
    q98_5 = models.CharField("Q98_5", max_length=200, blank=True, default=" ")
    q98_6 = models.CharField("Q98_6", max_length=200, blank=True, default=" ")
    q98_7 = models.CharField("Q98_7", max_length=200, blank=True, default=" ")
    q99_1 = models.CharField("Q99_1", max_length=200, blank=True, default=" ")
    q99_2 = models.CharField("Q99_2", max_length=200, blank=True, default=" ")
    q99_3 = models.CharField("Q99_3", max_length=200, blank=True, default=" ")
    q99_4 = models.CharField("Q99_4", max_length=200, blank=True, default=" ")
    q99_5 = models.CharField("Q99_5", max_length=200, blank=True, default=" ")
    q99_6 = models.CharField("Q99_6", max_length=200, blank=True, default=" ")
    q99_7 = models.CharField("Q99_7", max_length=200, blank=True, default=" ")
    q100_1 = models.CharField("Q100_1", max_length=200, blank=True, default=" ")
    q100_2 = models.CharField("Q100_2", max_length=200, blank=True, default=" ")
    q100_3 = models.CharField("Q100_3", max_length=200, blank=True, default=" ")
    q100_4 = models.CharField("Q100_4", max_length=200, blank=True, default=" ")
    q100_5 = models.CharField("Q100_5", max_length=200, blank=True, default=" ")
    q100_6 = models.CharField("Q100_6", max_length=200, blank=True, default=" ")
    q100_7 = models.CharField("Q100_7", max_length=200, blank=True, default=" ")
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    def get_absolute_url(self):
        return reverse('psytest:list', args=(self.id,))


# --- 심리검사응답.
class PsytestAnswer(models.Model):
    psytestsheet = models.ForeignKey(Psytestsheet, on_delete=models.CASCADE)
    client_nm = models.CharField('CLIENT NAME', max_length=100) # 수검자명
    target_nm = models.CharField('TARGET NAME', max_length=100, blank=True, null=True) # 대상자명, PAT의 경우 자녀이름, PAT-Y의 경우 부모
    birth_dt  = models.CharField('BIRTH DATE', max_length=8)    # 수검사 생년월일
    test_dt   = models.CharField('TEST DATE', max_length=8)     # 검사일자
    gender    = models.CharField('GENDER', max_length=1, blank=True, null=True)        # 성별 , (m, f)
    parent_dc = models.CharField('PARENT DC', max_length=1, blank=True, null=True)     # 양육자구분코드 , (1, 2)
    a1         = models.IntegerField(blank=True, null=True)
    a2         = models.IntegerField(blank=True, null=True)
    a3         = models.IntegerField(blank=True, null=True)
    a4         = models.IntegerField(blank=True, null=True)
    a5         = models.IntegerField(blank=True, null=True)
    a6         = models.IntegerField(blank=True, null=True)
    a7         = models.IntegerField(blank=True, null=True)
    a8         = models.IntegerField(blank=True, null=True)
    a9         = models.IntegerField(blank=True, null=True)
    a10        = models.IntegerField(blank=True, null=True)
    a11        = models.IntegerField(blank=True, null=True)
    a12        = models.IntegerField(blank=True, null=True)
    a13        = models.IntegerField(blank=True, null=True)
    a14        = models.IntegerField(blank=True, null=True)
    a15        = models.IntegerField(blank=True, null=True)
    a16        = models.IntegerField(blank=True, null=True)
    a17        = models.IntegerField(blank=True, null=True)
    a18        = models.IntegerField(blank=True, null=True)
    a19        = models.IntegerField(blank=True, null=True)
    a20        = models.IntegerField(blank=True, null=True)
    a21        = models.IntegerField(blank=True, null=True)
    a22        = models.IntegerField(blank=True, null=True)
    a23        = models.IntegerField(blank=True, null=True)
    a24        = models.IntegerField(blank=True, null=True)
    a25        = models.IntegerField(blank=True, null=True)
    a26        = models.IntegerField(blank=True, null=True)
    a27        = models.IntegerField(blank=True, null=True)
    a28        = models.IntegerField(blank=True, null=True)
    a29        = models.IntegerField(blank=True, null=True)
    a30        = models.IntegerField(blank=True, null=True)
    a31        = models.IntegerField(blank=True, null=True)
    a32        = models.IntegerField(blank=True, null=True)
    a33        = models.IntegerField(blank=True, null=True)
    a34        = models.IntegerField(blank=True, null=True)
    a35        = models.IntegerField(blank=True, null=True)
    a36        = models.IntegerField(blank=True, null=True)
    a37        = models.IntegerField(blank=True, null=True)
    a38        = models.IntegerField(blank=True, null=True)
    a39        = models.IntegerField(blank=True, null=True)
    a40        = models.IntegerField(blank=True, null=True)
    a41        = models.IntegerField(blank=True, null=True)
    a42        = models.IntegerField(blank=True, null=True)
    a43        = models.IntegerField(blank=True, null=True)
    a44        = models.IntegerField(blank=True, null=True)
    a45        = models.IntegerField(blank=True, null=True)
    a46        = models.IntegerField(blank=True, null=True)
    a47        = models.IntegerField(blank=True, null=True)
    a48        = models.IntegerField(blank=True, null=True)
    a49        = models.IntegerField(blank=True, null=True)
    a50        = models.IntegerField(blank=True, null=True)
    a51        = models.IntegerField(blank=True, null=True)
    a52        = models.IntegerField(blank=True, null=True)
    a53        = models.IntegerField(blank=True, null=True)
    a54        = models.IntegerField(blank=True, null=True)
    a55        = models.IntegerField(blank=True, null=True)
    a56        = models.IntegerField(blank=True, null=True)
    a57        = models.IntegerField(blank=True, null=True)
    a58        = models.IntegerField(blank=True, null=True)
    a59        = models.IntegerField(blank=True, null=True)
    a60        = models.IntegerField(blank=True, null=True)
    a61        = models.IntegerField(blank=True, null=True)
    a62        = models.IntegerField(blank=True, null=True)
    a63        = models.IntegerField(blank=True, null=True)
    a64        = models.IntegerField(blank=True, null=True)
    a65        = models.IntegerField(blank=True, null=True)
    a66        = models.IntegerField(blank=True, null=True)
    a67        = models.IntegerField(blank=True, null=True)
    a68        = models.IntegerField(blank=True, null=True)
    a69        = models.IntegerField(blank=True, null=True)
    a70        = models.IntegerField(blank=True, null=True)
    a71        = models.IntegerField(blank=True, null=True)
    a72        = models.IntegerField(blank=True, null=True)
    a73        = models.IntegerField(blank=True, null=True)
    a74        = models.IntegerField(blank=True, null=True)
    a75        = models.IntegerField(blank=True, null=True)
    a76        = models.IntegerField(blank=True, null=True)
    a77        = models.IntegerField(blank=True, null=True)
    a78        = models.IntegerField(blank=True, null=True)
    a79        = models.IntegerField(blank=True, null=True)
    a80        = models.IntegerField(blank=True, null=True)
    a81        = models.IntegerField(blank=True, null=True)
    a82        = models.IntegerField(blank=True, null=True)
    a83        = models.IntegerField(blank=True, null=True)
    a84        = models.IntegerField(blank=True, null=True)
    a85        = models.IntegerField(blank=True, null=True)
    a86        = models.IntegerField(blank=True, null=True)
    a87        = models.IntegerField(blank=True, null=True)
    a88        = models.IntegerField(blank=True, null=True)
    a89        = models.IntegerField(blank=True, null=True)
    a90        = models.IntegerField(blank=True, null=True)
    a91        = models.IntegerField(blank=True, null=True)
    a92        = models.IntegerField(blank=True, null=True)
    a93        = models.IntegerField(blank=True, null=True)
    a94        = models.IntegerField(blank=True, null=True)
    a95        = models.IntegerField(blank=True, null=True)
    a96        = models.IntegerField(blank=True, null=True)
    a97        = models.IntegerField(blank=True, null=True)
    a98        = models.IntegerField(blank=True, null=True)
    a99        = models.IntegerField(blank=True, null=True)
    a100       = models.IntegerField(blank=True, null=True)
    a101        = models.IntegerField(blank=True, null=True)
    a102        = models.IntegerField(blank=True, null=True)
    a103        = models.IntegerField(blank=True, null=True)
    a104        = models.IntegerField(blank=True, null=True)
    a105        = models.IntegerField(blank=True, null=True)
    a106        = models.IntegerField(blank=True, null=True)
    a107        = models.IntegerField(blank=True, null=True)
    a108        = models.IntegerField(blank=True, null=True)
    a109        = models.IntegerField(blank=True, null=True)
    a110        = models.IntegerField(blank=True, null=True)
    a111        = models.IntegerField(blank=True, null=True)
    a112        = models.IntegerField(blank=True, null=True)
    a113        = models.IntegerField(blank=True, null=True)
    a114        = models.IntegerField(blank=True, null=True)
    a115        = models.IntegerField(blank=True, null=True)
    a116        = models.IntegerField(blank=True, null=True)
    a117        = models.IntegerField(blank=True, null=True)
    a118        = models.IntegerField(blank=True, null=True)
    a119        = models.IntegerField(blank=True, null=True)
    a120        = models.IntegerField(blank=True, null=True)
    a121        = models.IntegerField(blank=True, null=True)
    a122        = models.IntegerField(blank=True, null=True)
    a123        = models.IntegerField(blank=True, null=True)
    a124        = models.IntegerField(blank=True, null=True)
    a125        = models.IntegerField(blank=True, null=True)
    a126        = models.IntegerField(blank=True, null=True)
    a127        = models.IntegerField(blank=True, null=True)
    a128        = models.IntegerField(blank=True, null=True)
    a129        = models.IntegerField(blank=True, null=True)
    a130        = models.IntegerField(blank=True, null=True)
    a131        = models.IntegerField(blank=True, null=True)
    a132        = models.IntegerField(blank=True, null=True)
    a133        = models.IntegerField(blank=True, null=True)
    a134        = models.IntegerField(blank=True, null=True)
    a135        = models.IntegerField(blank=True, null=True)
    a136        = models.IntegerField(blank=True, null=True)
    a137        = models.IntegerField(blank=True, null=True)
    a138        = models.IntegerField(blank=True, null=True)
    a139        = models.IntegerField(blank=True, null=True)
    a140        = models.IntegerField(blank=True, null=True)
    a141        = models.IntegerField(blank=True, null=True)
    a142        = models.IntegerField(blank=True, null=True)
    a143        = models.IntegerField(blank=True, null=True)
    a144        = models.IntegerField(blank=True, null=True)
    a145        = models.IntegerField(blank=True, null=True)
    a146        = models.IntegerField(blank=True, null=True)
    a147        = models.IntegerField(blank=True, null=True)
    a148        = models.IntegerField(blank=True, null=True)
    a149        = models.IntegerField(blank=True, null=True)
    a150        = models.IntegerField(blank=True, null=True)
    a151        = models.IntegerField(blank=True, null=True)
    a152        = models.IntegerField(blank=True, null=True)
    a153        = models.IntegerField(blank=True, null=True)
    a154        = models.IntegerField(blank=True, null=True)
    a155        = models.IntegerField(blank=True, null=True)
    a156        = models.IntegerField(blank=True, null=True)
    a157        = models.IntegerField(blank=True, null=True)
    a158        = models.IntegerField(blank=True, null=True)
    a159        = models.IntegerField(blank=True, null=True)
    a160        = models.IntegerField(blank=True, null=True)
    a161        = models.IntegerField(blank=True, null=True)
    a162        = models.IntegerField(blank=True, null=True)
    a163        = models.IntegerField(blank=True, null=True)
    a164        = models.IntegerField(blank=True, null=True)
    a165        = models.IntegerField(blank=True, null=True)
    a166        = models.IntegerField(blank=True, null=True)
    a167        = models.IntegerField(blank=True, null=True)
    a168        = models.IntegerField(blank=True, null=True)
    a169        = models.IntegerField(blank=True, null=True)
    a170        = models.IntegerField(blank=True, null=True)
    a171        = models.IntegerField(blank=True, null=True)
    a172        = models.IntegerField(blank=True, null=True)
    a173        = models.IntegerField(blank=True, null=True)
    a174        = models.IntegerField(blank=True, null=True)
    a175        = models.IntegerField(blank=True, null=True)
    a176        = models.IntegerField(blank=True, null=True)
    a177        = models.IntegerField(blank=True, null=True)
    a178        = models.IntegerField(blank=True, null=True)
    a179        = models.IntegerField(blank=True, null=True)
    a180        = models.IntegerField(blank=True, null=True)
    a181        = models.IntegerField(blank=True, null=True)
    a182        = models.IntegerField(blank=True, null=True)
    a183        = models.IntegerField(blank=True, null=True)
    a184        = models.IntegerField(blank=True, null=True)
    a185        = models.IntegerField(blank=True, null=True)
    a186        = models.IntegerField(blank=True, null=True)
    a187        = models.IntegerField(blank=True, null=True)
    a188        = models.IntegerField(blank=True, null=True)
    a189        = models.IntegerField(blank=True, null=True)
    a190        = models.IntegerField(blank=True, null=True)
    a191        = models.IntegerField(blank=True, null=True)
    a192        = models.IntegerField(blank=True, null=True)
    a193        = models.IntegerField(blank=True, null=True)
    a194        = models.IntegerField(blank=True, null=True)
    a195        = models.IntegerField(blank=True, null=True)
    a196        = models.IntegerField(blank=True, null=True)
    a197        = models.IntegerField(blank=True, null=True)
    a198        = models.IntegerField(blank=True, null=True)
    a199        = models.IntegerField(blank=True, null=True)
    a200        = models.IntegerField(blank=True, null=True)

    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
