# Generated by Django 3.0.8 on 2020-07-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psytest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psytest_nm', models.CharField(max_length=100, verbose_name='PSYTEST NAME')),
                ('description', models.CharField(blank=True, help_text='simple description text.', max_length=200, verbose_name='DESCRIPTION')),
                ('is_verify', models.BooleanField(default=False, verbose_name='IS VERIFY')),
                ('start_age', models.IntegerField(verbose_name='START_AGE')),
                ('end_age', models.IntegerField(verbose_name='END AGE')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
        ),
    ]
