# Generated by Django 3.0.8 on 2020-07-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsytestQuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no1', models.CharField(max_length=200, verbose_name='No1')),
                ('no2', models.CharField(max_length=200, verbose_name='No2')),
                ('no3', models.CharField(max_length=200, verbose_name='No3')),
                ('no4', models.CharField(max_length=200, verbose_name='No4')),
                ('no5', models.CharField(max_length=200, verbose_name='No5')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
        ),
    ]
