# Generated by Django 3.0.8 on 2020-07-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0002_psytestquestionlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsytestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no1', models.CharField(max_length=200, verbose_name='No1')),
                ('no2', models.CharField(max_length=200, verbose_name='No2')),
                ('no3', models.CharField(max_length=200, verbose_name='No3')),
                ('no1_1', models.CharField(max_length=200, verbose_name='No1_1')),
                ('no1_2', models.CharField(max_length=200, verbose_name='No1_2')),
                ('no1_3', models.CharField(max_length=200, verbose_name='No1_3')),
                ('no1_4', models.CharField(max_length=200, verbose_name='No1_4')),
                ('no1_5', models.CharField(max_length=200, verbose_name='No1_5')),
                ('no1_6', models.CharField(max_length=200, verbose_name='No1_6')),
                ('no1_7', models.CharField(max_length=200, verbose_name='No1_7')),
                ('no2_1', models.CharField(max_length=200, verbose_name='No2_1')),
                ('no2_2', models.CharField(max_length=200, verbose_name='No2_2')),
                ('no2_3', models.CharField(max_length=200, verbose_name='No2_3')),
                ('no2_4', models.CharField(max_length=200, verbose_name='No2_4')),
                ('no2_5', models.CharField(max_length=200, verbose_name='No2_5')),
                ('no2_6', models.CharField(max_length=200, verbose_name='No2_6')),
                ('no2_7', models.CharField(max_length=200, verbose_name='No2_7')),
                ('no3_1', models.CharField(max_length=200, verbose_name='No3_1')),
                ('no3_2', models.CharField(max_length=200, verbose_name='No3_2')),
                ('no3_3', models.CharField(max_length=200, verbose_name='No3_3')),
                ('no3_4', models.CharField(max_length=200, verbose_name='No3_4')),
                ('no3_5', models.CharField(max_length=200, verbose_name='No3_5')),
                ('no3_6', models.CharField(max_length=200, verbose_name='No3_6')),
                ('no3_7', models.CharField(max_length=200, verbose_name='No3_7')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
        ),
        migrations.DeleteModel(
            name='PsytestQuestionList',
        ),
    ]
