# Generated by Django 3.0.8 on 2020-07-20 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0005_auto_20200720_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='psytestquestion',
            name='testId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psytest.Psytest'),
            preserve_default=False,
        ),
    ]
