# Generated by Django 3.0.8 on 2020-07-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0006_psytestquestion_testid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psytest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='psytestquestion',
            options={'managed': True},
        ),
    ]
