# Generated by Django 3.0.8 on 2020-07-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0007_auto_20200720_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psytest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='psytestquestion',
            options={},
        ),
    ]
