# Generated by Django 3.0.8 on 2020-07-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0008_auto_20200720_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='psytest',
            name='no1',
            field=models.CharField(blank=True, max_length=200, verbose_name='No1'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no1_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='No1_1'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no1_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='No1_2'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no1_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='No1_3'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no1_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='No1_4'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no1_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='No1_5'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no1_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='No1_6'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no1_7',
            field=models.CharField(blank=True, max_length=200, verbose_name='No1_7'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no2',
            field=models.CharField(blank=True, max_length=200, verbose_name='No2'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no2_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='No2_1'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no2_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='No2_2'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no2_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='No2_3'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no2_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='No2_4'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no2_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='No2_5'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no2_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='No2_6'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no2_7',
            field=models.CharField(blank=True, max_length=200, verbose_name='No2_7'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no3',
            field=models.CharField(blank=True, max_length=200, verbose_name='No3'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no3_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='No3_1'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no3_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='No3_2'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no3_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='No3_3'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no3_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='No3_4'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no3_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='No3_5'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no3_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='No3_6'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='no3_7',
            field=models.CharField(blank=True, max_length=200, verbose_name='No3_7'),
        ),
    ]
