# Generated by Django 3.0.8 on 2020-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0009_auto_20200720_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psytest',
            name='no1',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no1_1',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no1_2',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no1_3',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no1_4',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no1_5',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no1_6',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no1_7',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no2',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no2_1',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no2_2',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no2_3',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no2_4',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no2_5',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no2_6',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no2_7',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no3',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no3_1',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no3_2',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no3_3',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no3_4',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no3_5',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no3_6',
        ),
        migrations.RemoveField(
            model_name='psytest',
            name='no3_7',
        ),
        migrations.AddField(
            model_name='psytest',
            name='q1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q1'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q1_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q1_1'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q1_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q1_2'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q1_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q1_3'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q1_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q1_4'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q1_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q1_5'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q1_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q1_6'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q1_7',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q1_7'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q2'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q2_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q2_1'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q2_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q2_2'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q2_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q2_3'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q2_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q2_4'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q2_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q2_5'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q2_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q2_6'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q2_7',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q2_7'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q3'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q3_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q3_1'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q3_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q3_2'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q3_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q3_3'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q3_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q3_4'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q3_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q3_5'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q3_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q3_6'),
        ),
        migrations.AddField(
            model_name='psytest',
            name='q3_7',
            field=models.CharField(blank=True, max_length=200, verbose_name='Q3_7'),
        ),
        migrations.DeleteModel(
            name='PsytestQuestion',
        ),
    ]
