# Generated by Django 3.0.8 on 2020-07-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0011_psytestanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psytestanswer',
            name='test_dt',
            field=models.CharField(max_length=100, verbose_name='TEST DATE'),
        ),
    ]
