# Generated by Django 3.0.8 on 2020-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0012_auto_20200720_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psytestanswer',
            name='a2',
            field=models.CharField(blank=True, max_length=200, verbose_name='A2'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a3',
            field=models.CharField(blank=True, max_length=200, verbose_name='A3'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a4',
            field=models.CharField(blank=True, max_length=200, verbose_name='A4'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a5',
            field=models.CharField(blank=True, max_length=200, verbose_name='A5'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a6',
            field=models.CharField(blank=True, max_length=200, verbose_name='A6'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a7',
            field=models.CharField(blank=True, max_length=200, verbose_name='A7'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a8',
            field=models.CharField(blank=True, max_length=200, verbose_name='A8'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a9',
            field=models.CharField(blank=True, max_length=200, verbose_name='A9'),
        ),
    ]
