# Generated by Django 3.0.8 on 2020-07-21 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0013_auto_20200720_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psytest',
            name='q1',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q1'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q1_1',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q1_1'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q1_2',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q1_2'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q1_3',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q1_3'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q1_4',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q1_4'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q1_5',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q1_5'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q1_6',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q1_6'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q1_7',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q1_7'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q2',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q2'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q2_1',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q2_1'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q2_2',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q2_2'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q2_3',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q2_3'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q2_4',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q2_4'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q2_5',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q2_5'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q2_6',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q2_6'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q2_7',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q2_7'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q3',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q3'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q3_1',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q3_1'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q3_2',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q3_2'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q3_3',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q3_3'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q3_4',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q3_4'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q3_5',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q3_5'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q3_6',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q3_6'),
        ),
        migrations.AlterField(
            model_name='psytest',
            name='q3_7',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Q3_7'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a1',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A1'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a10',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A10'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a11',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A11'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a12',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A12'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a13',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A13'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a14',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A14'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a15',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A15'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a16',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A16'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a17',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A17'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a18',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A18'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a19',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A19'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a2',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A2'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a20',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A20'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a21',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A21'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a22',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A22'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a23',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A23'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a24',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A24'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a25',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A25'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a26',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A26'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a27',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A27'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a28',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A28'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a29',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A29'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a3',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A3'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a30',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A30'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a31',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A31'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a32',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A32'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a33',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A33'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a34',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A34'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a35',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A35'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a36',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A36'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a37',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A37'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a38',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A38'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a39',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A39'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a4',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A4'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a40',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A40'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a41',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A41'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a42',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A42'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a43',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A43'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a44',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A44'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a45',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A45'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a46',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A46'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a47',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A47'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a48',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A48'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a49',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A49'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a5',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A5'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a50',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A50'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a51',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A51'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a52',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A52'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a53',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A53'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a54',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A54'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a55',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A55'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a56',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A56'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a57',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A57'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a58',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A58'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a59',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A59'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a6',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A6'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a60',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A60'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a61',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A61'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a62',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A62'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a63',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A63'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a64',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A64'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a65',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A65'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a66',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A66'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a67',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A67'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a68',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A68'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a69',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A69'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a7',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A7'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a70',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A70'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a71',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A71'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a72',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A72'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a73',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A73'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a74',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A74'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a75',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A75'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a76',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A76'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a77',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A77'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a78',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A78'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a79',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A79'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a8',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A8'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a80',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A80'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a81',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A81'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a82',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A82'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a83',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A83'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a84',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A84'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a85',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A85'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a86',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A86'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a87',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A87'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a88',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A88'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a89',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A89'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a9',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A9'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a90',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A90'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a91',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A91'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a92',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A92'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a93',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A93'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a94',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A94'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a95',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A95'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a96',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A96'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a97',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A97'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a98',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A98'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='a99',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='A99'),
        ),
        migrations.AlterField(
            model_name='psytestanswer',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytest.Psytest'),
        ),
    ]
