# Generated by Django 3.0.8 on 2020-07-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0017_auto_20200724_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psytestanswer',
            name='psytestsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytest.Psytestsheet'),
        ),
    ]
