# Generated by Django 3.0.8 on 2020-07-26 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psytest', '0018_auto_20200724_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='psytestanswer',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='CREATE DATE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psytestanswer',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE'),
        ),
    ]
